BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "gamestats" (
	"id"	INTEGER,
	"skatername"	STRING NOT NULL UNIQUE,
	"teamname"	STRING NOT NULL UNIQUE,
	"skaterpoints"	STRING NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
